// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/features/sof/domain/entities/sof_users_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 8279558010659357710),
      name: 'SofUserEntity',
      lastPropertyId: const IdUid(6, 6957847708007075916),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3464665846915180310),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3861215089071409499),
            name: 'reputation',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7693145800658084585),
            name: 'userId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1377589323541506476),
            name: 'location',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2376324940473660933),
            name: 'profileImage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 6957847708007075916),
            name: 'displayName',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 8279558010659357710),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    SofUserEntity: EntityDefinition<SofUserEntity>(
        model: _entities[0],
        toOneRelations: (SofUserEntity object) => [],
        toManyRelations: (SofUserEntity object) => {},
        getId: (SofUserEntity object) => object.id,
        setId: (SofUserEntity object, int id) {
          object.id = id;
        },
        objectToFB: (SofUserEntity object, fb.Builder fbb) {
          final locationOffset = object.location == null
              ? null
              : fbb.writeString(object.location!);
          final profileImageOffset = object.profileImage == null
              ? null
              : fbb.writeString(object.profileImage!);
          final displayNameOffset = object.displayName == null
              ? null
              : fbb.writeString(object.displayName!);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.reputation);
          fbb.addInt64(2, object.userId);
          fbb.addOffset(3, locationOffset);
          fbb.addOffset(4, profileImageOffset);
          fbb.addOffset(5, displayNameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = SofUserEntity(
              reputation: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 6),
              userId: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 8),
              location: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              profileImage: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              displayName: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [SofUserEntity] entity fields to define ObjectBox queries.
class SofUserEntity_ {
  /// see [SofUserEntity.id]
  static final id =
      QueryIntegerProperty<SofUserEntity>(_entities[0].properties[0]);

  /// see [SofUserEntity.reputation]
  static final reputation =
      QueryIntegerProperty<SofUserEntity>(_entities[0].properties[1]);

  /// see [SofUserEntity.userId]
  static final userId =
      QueryIntegerProperty<SofUserEntity>(_entities[0].properties[2]);

  /// see [SofUserEntity.location]
  static final location =
      QueryStringProperty<SofUserEntity>(_entities[0].properties[3]);

  /// see [SofUserEntity.profileImage]
  static final profileImage =
      QueryStringProperty<SofUserEntity>(_entities[0].properties[4]);

  /// see [SofUserEntity.displayName]
  static final displayName =
      QueryStringProperty<SofUserEntity>(_entities[0].properties[5]);
}
